<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\TapAi.Module.Identity.Infrastructure\TapAi.Module.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\TapAi.Module.Identity.Persistence\TapAi.Module.Identity.Persistence.csproj" />
  </ItemGroup>

</Project>
