<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlocks\TapAi.Shared.Application\TapAi.Shared.Application.csproj" />
    <ProjectReference Include="..\TapAi.Module.Identity.Domain\TapAi.Module.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
